{% set name = "sos-papermill" %}
{% set version = "0.1.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 90e328af7d8640b5f903bd07318276a1d31a66d41ee95bdad92a077e5f7ae18c

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - sos-notebook
    - python >=3.6
    - papermill

test:
  requires:
    - nose
    - pytest
    - nbformat
    - mock
  imports:
    - sos_papermill

about:
  home: https://github.com/vatlab/sos-papermill
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "SoS engine for papermill"
  doc_url: https://vatlab.github.io/sos-docs/
  dev_url: https://github.com/vatlab/sos-papermill

extra:
  recipe-maintainers:
    - BoPeng
