{% set name = "sos-papermill" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1f94ffadf4b7884983500acd9c4c633f0ff4a504c1d1a8b7c0a09e379c898923

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - sos-notebook
    - python >=3.6
    - papermill

test:
  requires:
    - nose
    - pytest
    - nbformat
    - mock
  imports:
    - sos_papermill

about:
  home: https://github.com/vatlab/sos-papermill
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: SoS engine for papermill
  doc_url: https://vatlab.github.io/sos-docs/
  dev_url: https://github.com/vatlab/sos-papermill

extra:
  recipe-maintainers:
    - BoPeng
