travis:
  secure:
    BINSTAR_TOKEN: 0OKbkSpXA9tKYAeq54aojCYusgKpZUJe1JbDb6xi9OIs1kDOUE5vaQ8Slt9xqNbBFnW/GZrq18EYEkHaxkp2ihIlDBCvUrdYAdcQOJnPXSc+nHWd4pTMW3b5NN/UZPhhiVrV4eokJxhVxz+T0qjKPNZEyynrEGyQMdE3CWqo5XBj7e9SmOtO9bvP1Jupmgz2D/TCoqCjbrrrJ2tFAmbydCh6BNgoRV7KrUiozzO4Wy+CYRGMmHPtvfyksQxWki9jV2FkLJtcxbslXeSZSf0oppTtqResgjHTlyEj4RR3BabL3NrxIsuwtcNqnmrn2bOLFONWTJswVCNIEtbwm2wphiXsOHk2oRYT1mAhoemZLHp8bUIeJWqrk08azSn9+XKtWjm3Ts+vs7A6yLK+wtY9YIEnMvjlXHgZYrSbHZXSCqXtbfVODKryD4GLj6UD9cuyhpJOf4CRJ+cHTLDhtOYKH0d2VXCrZoZkLBYxPLoSISot1ayCapKFYxGx3fK798kWBcBc4yVTuDlPW7rI7iQh9LfTEWW76s6CCQYRoMmJJ5+4QDORNYMdhkW77MiCKJ8cTXxGwW8Ej+0RzB7vM67oIQkwiPGsgmIIEYq50+O2ZZqPq8nlxaUJDQgTyeVevztih9XjVBMkhrrUhyNh0U85uMaMbpCwI/T+LtFovip4bsU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
